In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

In [9]:
laptops = pd.read_csv('laptops.csv')

In [14]:
len(laptops)

2160

In [18]:
len(laptops.Brand.unique())

27

In [24]:
laptops.isna().any()

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

In [30]:
laptops[laptops['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [33]:
laptops.Screen.median()

15.6

In [37]:
laptops.Screen.value_counts()

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.50      19
13.40      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
14.40       6
12.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.10       1
10.95       1
Name: count, dtype: int64

In [41]:
laptops_fillna = laptops.fillna(15.60)

In [42]:
laptops_fillna.Screen.value_counts()

Screen
15.60    1013
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.50      19
13.40      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
14.40       6
12.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.10       1
10.95       1
Name: count, dtype: int64

In [44]:
laptops_fillna.Screen.median()

15.6

In [120]:
innjoo = laptops_fillna[laptops['Brand'] == 'Innjoo']

In [171]:
arrx = innjoo[['RAM','Storage','Screen']].values
arrx

array([[   8. ,  512. ,   15.6],
       [   8. ,  256. ,   15.6],
       [   8. ,  256. ,   15.6],
       ...,
       [  32. , 1000. ,   17.3],
       [  16. , 1000. ,   13.4],
       [  16. ,  256. ,   13.4]])

In [172]:
import numpy as np

In [173]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [185]:
arrx_t = np.transpose(arrx)
arrx_t

array([[   8. ,    8. ,    8. , ...,   32. ,   16. ,   16. ],
       [ 512. ,  256. ,  256. , ..., 1000. , 1000. ,  256. ],
       [  15.6,   15.6,   15.6, ...,   17.3,   13.4,   13.4]])

In [186]:
xtx = matrix_matrix_multiplication(arrx_t, arrx)
xtx

array([[7.23420000e+05, 2.56347520e+07, 5.14286600e+05],
       [2.56347520e+07, 1.04973173e+09, 1.99103300e+07],
       [5.14286600e+05, 1.99103300e+07, 5.00128312e+05]])

In [187]:
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 1.09915475e-05, -2.20639891e-07, -2.51893871e-06],
       [-2.20639891e-07,  8.31868438e-09, -1.04284462e-07],
       [-2.51893871e-06, -1.04284462e-07,  8.74134571e-06]])

In [184]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [193]:
step = matrix_matrix_multiplication(xtx_inv, y)
step

AssertionError: 

In [190]:
xtx_inv.shape

(3, 3)

In [191]:
arrx_t.shape

(3, 2160)

In [192]:
step.shape

(3, 2160)

In [170]:
matrix_vector_multiplication(step, y)

AssertionError: 